Fix: typeorm driver mysql to mysql2
- The following error occurs as mysql version is updated to 8.3
- Error during schema synchronization:
  Error: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client
- When synchronizing db to typeorm, env was not applied properly, so i imported env config to AppDataSource.