Fix: Cannot find module error and EntityMetadataNotFoundError: No metadata for "project" was found error
- tsconfig-paths README.md said "execute the compiled files with node (or ts-node), it will only look in the node_modules folders all the way up to the root of the filesystem and thus will not find the modules specified by paths in tsconfig."
- Therefore, if production run, it points to the src directory, so cannot find module error or EntityMetaDataNotFoundError occurs
- so point to the dist folder through the "TS_NODE_BASEURL=./dist" settings in package.json script
- reference: https://github.com/dividab/tsconfig-paths, https://github.com/nestjs/nest/issues/986